### ISSUE TITLE
Autoload

### ISSUE THREAD

**Issue by ozdemircili** [agperson/zabbix-webroots-dashboard#1]
Hi,

I`m getting the following error:

PHP Warning:  require(vendor/autoload.php): failed to open stream: No such file or directory in /var/www/zabbix/services.php on line 3
PHP Fatal error:  require(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/zabbix/services.php on line 3

What may be the problem?

Thanks in advance.

**Comment by agperson** [comment]
You will need to run composer to populate that directory, see https://getcomposer.org/ for more information.

**Comment by exceruby** [comment]
You can populate vender directory with following commands.

<pre>
cd YOUR_ZABBIX-WEBROOTS-DASHBOARD_DIR
curl -s http://getcomposer.org/installer | php
php composer.phar install
</pre>

**Comment by agperson** [comment]
Thanks, I have updated the README with install details as well as a paragraph about customizing the dashboard.
